export { DownloadIcon } from './DownloadIcon'
export { EmailIcon } from './EmailIcon'
export { MapPinIcon } from './MapPinIcon'
export { LinkedinIcon } from './LinkedinIcon'
export { CalendarIcon } from './CalendarIcon'
export { URLLinkIcon } from './LinkIcon'
export { SendIcon } from './SendIcon'
export { SpinnerIcon } from './SpinnerIcon'

export * from './FallbackProjectIcons'
export * from './ProjectChipsIcons'
export * from './stack'
