import type { Experiences } from 'src/types/experiences.types'

export const workExperiences: Experiences[] = [
  {
    logo: '/images/dekra_logo.webp',
    title: 'Frontend Developer & UX/UI Designer',
    company: 'DEKRA Digital & Product Solutions',
    period: 'August 2023 - Present',
    description:
      'Design and development of web applications supporting AI solutions (e.g., chatbots, image recognition tools, internal dashboards). Bridging frontend development with UX/UI design responsibilities, while collaborating with international teams across different countries using English as the main working language.',
    technologies: [
      'React',
      'Angular',
      'Figma',
      'TypeScript',
      'Tailwind CSS',
      'Excalidraw',
      'Git',
      'HTML',
      'CSS',
      'Azure DevOps',
      'Jira',
      'React Native',
      'Java',
      'Kotlin',
      'Python',
      'Spring Boot',
      'Microsoft Azure',
    ],
    location: 'Málaga, Spain',
  },
  {
    title: 'Software Developer',
    period: 'January 2023 - June 2023',
    description:
      'Delivered full-stack features for enterprise-level applications using a Java/Spring Boot backend, Angular frontend and Android development. Optimized application responsiveness and ensured high-quality code through unit testing and agile collaboration within an international cross-functional team.',
    technologies: [
      'Java',
      'Kotlin',
      'Angular',
      'Spring Boot',
      'Microsoft Azure',
      'PostgreSQL',
      'JUnit',
      'RxJS',
      'Android Development',
      'Python',
      'Git',
      'Azure DevOps',
      'Postman',
      'Tailwind CSS',
      'HTML',
      'CSS',
      'TypeScript',
    ],
    location: 'Stuttgart, Germany & Málaga, Spain',
  },
  {
    title: 'AI Intern',
    period: 'March 2022 - June 2022',
    description:
      'Executed an intensive upskilling program in Artificial Intelligence and Machine Learning, transitioning from theoretical foundations to practical application. Supported the AI department in data preprocessing and model testing, contributing to the optimization of internal data pipelines while gaining hands-on experience with Microsoft Azure AI services.',
    technologies: [
      'Python',
      'Microsoft Azure',
      'Artificial Intelligence',
      'Machine Learning',
    ],
    location: 'Málaga, Spain',
  },
]

export const educationExperiences: Experiences[] = [
  {
    logo: '/images/zaidin.png',
    title: 'Curso de Especialización, Inteligencia Artificial & Big Data',
    company: 'IES Zaidín-Vergeles',
    period: 'September 2023 - June 2025',
    description:
      'Design and development of web applications supporting AI solutions (e.g., chatbots, image recognition tools, internal dashboards). Bridging frontend development with UX/UI design responsibilities, while collaborating with international teams across different countries using English as the main working language.',
    technologies: [
      'Python',
      'R',
      'Machine Learning',
      'Data Analysis',
      'PowerBI',
      'AWS',
      'Amazon EMR',
      'Apache Hadoop',
      'Apache Spark',
      'Jupyter Notebook',
      'Google Colab',

      'Artificial Intelligence',
    ],
    location: 'Granada, Spain (Remote learning)',
  },
  {
    logo: '/images/cpifpalanturing_logo.webp',
    title: 'CFGS, Desarrollo de Aplicaciones Multiplataforma',
    company: 'Centro Público Integrado de FP Alan Turing',
    period: 'September 2021 - June 2023',
    description:
      'Developed and maintained multiple client projects, implemented responsive designs, and integrated third-party APIs for enhanced functionality.',
    technologies: [
      'Java',
      'Angular',
      'Kotlin',
      'Android Development',
      'Git',
      'GitHub',
      'Ionic Framework',
      'JSP',
      'MAUI',
      'C#',
      'HTML',
      'CSS',
      'JavaScript',
      'TypeScript',
      'SQL',
      'MySQL',
      'Odoo',
    ],
    location: 'Málaga TechPark, Málaga, Spain',
  },
  {
    logo: '/images/iesmartinaldehuela.webp',
    title: 'Bachillerato, Tecnología de la ingeniería',
    company: 'IES Martín Aldehuela',
    period: 'September 2019 - June 2021',
    technologies: [],
    location: 'Málaga, Spain',
  },
  {
    title: 'Educación Secundaria Obligatoria (ESO), Científico-tecnológico',
    period: 'September 2015 - June 2019',
    technologies: [],
    location: 'Málaga, Spain',
  },
]
